apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: online-boutique-frontend
  namespace: online-boutique
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: frontend
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: online-boutique-cartservice
  namespace: online-boutique
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: cartservice
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: online-boutique-productcatalog
  namespace: online-boutique
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: productcatalogservice
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: online-boutique-currencyservice
  namespace: online-boutique
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: currencyservice
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: online-boutique-paymentservice
  namespace: online-boutique
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: paymentservice
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: online-boutique-shippingservice
  namespace: online-boutique
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: shippingservice
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: online-boutique-emailservice
  namespace: online-boutique
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: emailservice
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: online-boutique-checkoutservice
  namespace: online-boutique
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: checkoutservice
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: online-boutique-recommendationservice
  namespace: online-boutique
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: recommendationservice
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: online-boutique-adservice
  namespace: online-boutique
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: adservice