replicaCount: 1

global:
  platform: aws
  environment: dev

frontend:
  service:
    type: ClusterIP
  livenessProbe:
    httpGet:
      path: /healthz
      port: 8080
    initialDelaySeconds: 30
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /readyz
      port: 8080
    initialDelaySeconds: 5
    periodSeconds: 5

podDisruptionBudget:
  enabled: true
  minAvailable: 1

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

networkPolicy:
  enabled: true
  allowExternal: true
