replicaCount: 3

global:
  platform: aws
  environment: prod

frontend:
  service:
    type: ClusterIP
  livenessProbe:
    httpGet:
      path: /healthz
      port: 8080
    initialDelaySeconds: 30
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /readyz
      port: 8080
    initialDelaySeconds: 5
    periodSeconds: 5

podDisruptionBudget:
  enabled: true
  minAvailable: 2

resources:
  limits:
    cpu: 2
    memory: 2Gi
  requests:
    cpu: 1
    memory: 1Gi

networkPolicy:
  enabled: true
  allowExternal: true
